
/* eslint-disable react/react-in-jsx-scope */
// 此处为图标的mock数据
const menuList = [
    "appstore",
    "setting",
    "menu",
    "apartment",
    "team",
    "user",
    "smile",
    "bell",
    "account-book",
    "dashboard",
    "database",
    "message",
    "cluster",
    "paper-clip",
    "unlock",
    "tags",
    "history",
    "safety",
    "profile",
    "file",
    "alert",
    "folder",
    "android",
    "apple",
    "windows",
    "github",
    "api",
    "book",
    "cloud",
    "environment",
    "insurance",
    "mail",
    "printer",
    "barcode",
    "qrcode",
    "cloud-upload",
    "audit",
    "safety-certificate"
];

export default menuList;